### ISSUE TITLE
Comparator-based framework: Checklist for version 1

### ISSUE THREAD

**Issue by androlo** [androlo/rope_engineering#14]
### Core

- [x] Introduction
- [x] Comparators
- [x] Base unit functions
- [x] Base unit function algebra
- [ ] Derived unit functions
- [ ] Examples

### Finalization

- [ ] Document structure
- [ ] Formalize all proofs
- [ ] Check all indexes
- [ ] Typos
- [ ] Attribution

**Comment by androlo** [comment]
Checking is to say that the bulk is done, and ready for a final pass once everything is in place.

**Comment by androlo** [comment]
Change after mega refactoring. Put measurement matrices and units as functions and the whole lot in. Gonna take some time to clean up and refactor. Removed dimensional analysis for now.

**Comment by androlo** [comment]
Removed types. They may be added back in later but as of right now it feels like they make things more complicated, and could seem a bit to "programmy" to some people.

**Comment by androlo** [comment]
Removed separate chapter on matrices now that they are worked into the main text.

**Comment by androlo** [comment]
The first milestone will be to get everything up to and including derived units done.

**Comment by androlo** [comment]
V1 is what it is, not gonna do more. Closing.
