### ISSUE TITLE
Comparator-based framework: Checklist for version 2

### ISSUE THREAD

**Issue by androlo** [androlo/rope_engineering#18]
### Core
- [ ] Comparator series analysis
- [ ] Dimensional analysis
- [ ] Graphs

### Finalization

- [ ] Formalize all proofs
- [ ] Check all indexes
- [ ] Typos
- [ ] Attribution

**Comment by androlo** [comment]
Closing as there will not be a V2.
